int32 id                    # Unique ID of the parking spot
uint8 status                # Status of the parking spot 0 = free , 1 = occupied, 2 = booked
float32 x                   # X Position in the Model City coordinate system
float32 y                   # Y Position in the Model City coordinate system
float32 width               # Width in m (X size)
float32 length              # Length in m (Y Size)
float32 distance            # distance in m